name: flutter_im
description: IM通讯的 中台办公相关

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # toast
  fluttertoast: ^8.2.1
  # 启动的logo
  icons_launcher: ^2.1.0
  getx_translator: ^1.0.2
  # 网络请求
  cached_network_image: ^3.2.3
  # 存储相关
  shared_preferences: ^2.1.0
  # 网络请求
  dio: ^5.1.1
  # 日志
  logger: ^1.3.0
  # loading
  flutter_easyloading: ^3.0.5
  # 弹框
  adaptive_dialog: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
